//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 动态壁纸 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class SetFile : global::System.Configuration.ApplicationSettingsBase {
        
        private static SetFile defaultInstance = ((SetFile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SetFile())));
        
        public static SetFile Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// 是否初次启动应用程序
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("是否初次启动应用程序")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFristStatUp {
            get {
                return ((bool)(this["IsFristStatUp"]));
            }
            set {
                this["IsFristStatUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\GengG\\Pictures\\Snapshots of Videos\\Snapshot.png")]
        public string DefaultPath {
            get {
                return ((string)(this["DefaultPath"]));
            }
            set {
                this["DefaultPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFullScreenOfMainWindow {
            get {
                return ((bool)(this["IsFullScreenOfMainWindow"]));
            }
            set {
                this["IsFullScreenOfMainWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte DefaultFullScreen {
            get {
                return ((byte)(this["DefaultFullScreen"]));
            }
            set {
                this["DefaultFullScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\Video\\动态壁纸\\壁纸\\DGVB.mp4")]
        public string TempViewPath {
            get {
                return ((string)(this["TempViewPath"]));
            }
            set {
                this["TempViewPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NowVideoTimes {
            get {
                return ((int)(this["NowVideoTimes"]));
            }
            set {
                this["NowVideoTimes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NowPlayingPath {
            get {
                return ((string)(this["NowPlayingPath"]));
            }
            set {
                this["NowPlayingPath"] = value;
            }
        }
    }
}
